export type Area = "southtowns" | "city";
export type EventKind =
  | "All activities"
  | "Fairs & festivals"
  | "Markets & food"
  | "Live music"
  | "Sports & active"
  | "Outdoors"
  | "Museums & culture"
  | "Community"
  | "Library";
export type SettingFilter = "all" | "indoor" | "outdoor";
export type Vibe = "all" | "outside" | "kids" | "food" | "evening" | "rain" | "drive";
export type Sort = "recommended" | "closest";

export type EventPick = {
  id: string;
  area: Area;
  town: string;
  day: string;
  date: string;
  dateKey?: string;
  time: string;
  title: string;
  venue: string;
  distance: number;
  description: string;
  cost: string;
  source: string;
  url: string;
  mapUrl: string;
  tags: string[];
  accent: string;
  image?: string;
  today?: boolean;
  kind?: Exclude<EventKind, "All activities">;
  setting?: "indoor" | "outdoor" | "both";
  priority?: number;
  lat?: number;
  lon?: number;
  /** How precisely the venue was placed: exact venue, town centroid, or unknown. */
  distancePrecision?: "venue" | "town" | "region";
};

/**
 * The bundled snapshot is a point-in-time copy, not live data. Surfacing the
 * date lets the UI say so plainly instead of presenting stale listings as today's.
 */
export const SNAPSHOT_DATE = "2026-08-12";

const legacyFallbackEvents: EventPick[] = [
  { id: "erie-fair", area: "southtowns", town: "Hamburg", day: "TODAY", date: "Wed, Aug 12", time: "11 AM–10 PM · midway noon–11", title: "Erie County Fair · Opening Day", venue: "Hamburg Fairgrounds", distance: 6, description: "Rides, farm animals, 4-H exhibits, food and opening-day community spirit make this the Southtowns’ biggest family outing.", cost: "Free with 4+ canned goods · otherwise $19 adult", source: "Erie County Fair", url: "https://www.ecfair.org/p/info/admissionparking", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hamburg+Fairgrounds+5600+McKinley+Parkway+Hamburg+NY", tags: ["Fair", "Kids", "Food"], accent: "coral", image: "/events/erie-county-fair.jpg", today: true, setting: "both" },
  { id: "op-reptiles", area: "southtowns", town: "Orchard Park", day: "TODAY", date: "Wed, Aug 12", time: "2 PM", title: "Reptiles Around the World", venue: "Orchard Park Public Library", distance: 1, description: "Repco Wildlife Encounters brings live reptiles to the library for a close-to-home, all-ages animal program.", cost: "Free · registration required", source: "B&ECPL", url: "https://www.buffalolib.org/orchard-park-public-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Orchard+Park+Public+Library+Orchard+Park+NY", tags: ["Animals", "Kids", "Indoor"], accent: "mint", today: true, setting: "indoor" },
  { id: "elma-fossils", area: "southtowns", town: "Elma", day: "TODAY", date: "Wed, Aug 12", time: "2–3 PM", title: "Fossil Frenzy Play Cafe", venue: "Elma Public Library", distance: 10, description: "Handle fossils and explore a digital microscope in a hands-on, all-ages library play session.", cost: "Free · no registration", source: "B&ECPL", url: "https://www.buffalolib.org/locations-hours/elma-public-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Elma+Public+Library+Elma+NY", tags: ["Science", "Kids", "Drop-in"], accent: "sky", today: true, setting: "indoor" },
  { id: "hamburg-storytime", area: "southtowns", town: "Hamburg", day: "TODAY", date: "Wed, Aug 12", time: "10:30 or 11:30 AM", title: "Hamburg Public Library Story Time", venue: "Hamburg Public Library", distance: 12, description: "Themed stories, crafts and movement for young children and caregivers in a welcoming indoor setting.", cost: "Free · registration required", source: "B&ECPL", url: "https://www.buffalolib.org/locations-hours/hamburg-public-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hamburg+Public+Library+102+Buffalo+Street+Hamburg+NY", tags: ["Storytime", "Kids", "Indoor"], accent: "sun", today: true, setting: "indoor" },
  { id: "destination-dinosaur", area: "city", town: "Buffalo", day: "TODAY", date: "Wed, Aug 12", time: "10 AM–5 PM", title: "Destination Dinosaur", venue: "Buffalo Zoo", distance: 17, description: "Walk a trail of life-size animatronic dinosaurs, dig for fossils and catch educational dino shows at noon and 2 PM.", cost: "$25.95 adult · $19.95 child", source: "Buffalo Zoo", url: "https://buffalozoo.org/event/destination-dinosaur/2026-08-12/", mapUrl: "https://www.google.com/maps/search/?api=1&query=Buffalo+Zoo+300+Parkside+Avenue+Buffalo+NY", tags: ["Animals", "Dinosaurs", "All day"], accent: "purple", today: true, setting: "both" },
  { id: "lake-shore-storytime", area: "southtowns", town: "Lakeshore", day: "THU", date: "Thu, Aug 13", time: "10 AM", title: "StoryTime Shookup", venue: "Lake Shore Branch Library · Hamburg", distance: 9, description: "Silly stories, music, movement and a craft make this a breezy morning for preschoolers and caregivers.", cost: "Free · no registration", source: "B&ECPL", url: "https://www.buffalolib.org/locations-hours/lake-shore-branch-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Lake+Shore+Branch+Library+4857+Lake+Shore+Road+Hamburg+NY", tags: ["Storytime", "Music", "Kids"], accent: "mint", setting: "indoor" },
  { id: "boston-bubbles", area: "southtowns", town: "Boston", day: "THU", date: "Thu, Aug 13", time: "4:30–6:30 PM", title: "Annual Bubble Day", venue: "Boston Free Library", distance: 17, description: "Test giant bubbles, experiment with wands and make a soapy science memory together.", cost: "Free · registration required", source: "B&ECPL", url: "https://www.buffalolib.org/locations-hours/boston-free-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Boston+Free+Library+9475+Boston+State+Road+Boston+NY", tags: ["Science", "All ages", "Outdoor"], accent: "sky", setting: "outdoor" },
  { id: "hamburg-games", area: "southtowns", town: "Hamburg", day: "THU", date: "Thu, Aug 13", time: "5–7 PM", title: "Family Game Night", venue: "Hamburg Public Library", distance: 12, description: "Board games and low-key family competition make an easy after-dinner outing close to home.", cost: "Free library program", source: "B&ECPL", url: "https://www.buffalolib.org/locations-hours/hamburg-public-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hamburg+Public+Library+102+Buffalo+Street+Hamburg+NY", tags: ["Games", "Kids", "Indoor"], accent: "coral", setting: "indoor" },
  { id: "dinosaur-escape", area: "southtowns", town: "Orchard Park", day: "ALL WEEK", date: "Sat, Aug 8–Sat, Aug 22", time: "During library hours", title: "Dinosaur Escape!", venue: "Orchard Park Public Library", distance: 1, description: "Solve a 45-minute dinosaur-themed escape room with your family without leaving Orchard Park.", cost: "Free · registration required", source: "B&ECPL", url: "https://www.buffalolib.org/orchard-park-public-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Orchard+Park+Public+Library+Orchard+Park+NY", tags: ["Puzzle", "Dinosaurs", "Indoor"], accent: "purple", setting: "indoor" },
  { id: "south-buffalo-market", area: "southtowns", town: "South Buffalo", day: "SUN", date: "Sun, Aug 16", time: "9 AM–1 PM", title: "South Buffalo Farmers Market", venue: "Cazenovia Park Casino lawn", distance: 12, description: "Local growers and makers, live music, free yoga and neighborhood bike rides make Sunday morning feel neighborly.", cost: "Free entry", source: "South Buffalo Farmers Market", url: "https://southbuffalofarmersmarket.com/visit-the-market", mapUrl: "https://www.google.com/maps/search/?api=1&query=Cazenovia+Park+Casino+Buffalo+NY", tags: ["Market", "Food", "Music"], accent: "sun", setting: "outdoor" },
  { id: "op-dog", area: "southtowns", town: "Orchard Park", day: "WED", date: "Wed, Aug 19", time: "4–5 PM", title: "Read to a Dog", venue: "Orchard Park Public Library", distance: 1, description: "Children can practice reading with a certified therapy dog in a relaxed, confidence-building library visit.", cost: "Free · drop-in", source: "B&ECPL", url: "https://www.buffalolib.org/locations-hours/orchard-park-public-library", mapUrl: "https://www.google.com/maps/search/?api=1&query=Orchard+Park+Public+Library+Orchard+Park+NY", tags: ["Animals", "Reading", "Kids"], accent: "mint", setting: "indoor" },
  { id: "eden-books", area: "southtowns", town: "Eden", day: "TUE", date: "Tue, Aug 18", time: "4 PM", title: "Chapter Books, Cookies & Coloring", venue: "Eden Library", distance: 16, description: "A relaxed reading-and-craft hour pairs chapter-book conversation with cookies and coloring for young readers.", cost: "Free library program", source: "B&ECPL", url: "https://www.buffalolib.org/eden-library-calendar", mapUrl: "https://www.google.com/maps/search/?api=1&query=Eden+Library+2901+East+Church+Street+Eden+NY", tags: ["Reading", "Crafts", "Kids"], accent: "sun", setting: "indoor" },
  { id: "shakespeare", area: "city", town: "Buffalo", day: "THU–SUN", date: "Thu, Aug 13–Sun, Aug 16", time: "7 PM", title: "The Taming of the Shrew", venue: "Shakespeare Hill · Delaware Park", distance: 16, description: "Pack a picnic for Buffalo’s beloved free Shakespeare tradition under the trees beside Hoyt Lake.", cost: "Free · non-ticketed", source: "Shakespeare in Delaware Park", url: "https://shakespeareindelawarepark.org/mainstage/", mapUrl: "https://www.google.com/maps/search/?api=1&query=Shakespeare+Hill+Delaware+Park+Buffalo+NY", tags: ["Theater", "Outdoor", "Picnic"], accent: "coral", setting: "outdoor" },
  { id: "canalside-kids", area: "city", town: "Buffalo", day: "FRI", date: "Fri, Aug 14", time: "10:30 AM", title: "Canalside for Kids Walking Tour", venue: "Waterway of Change Museum", distance: 19, description: "A guide turns the waterfront’s history into a one-mile, stroller-friendly adventure designed especially for ages 5–10.", cost: "Free · registration required", source: "Explore Buffalo", url: "https://explorebuffalo.org/waterfront/canalside-for-kids/", mapUrl: "https://www.google.com/maps/search/?api=1&query=Longshed+Building+Canalside+Buffalo+NY", tags: ["History", "Kids", "Outdoor"], accent: "sky", setting: "outdoor" },
  { id: "wild-robot", area: "city", town: "Buffalo", day: "FRI", date: "Fri, Aug 14", time: "7–10 PM · film at sunset", title: "Family Movie Night: The Wild Robot", venue: "Prospect Park", distance: 17, description: "Bring blankets and chairs for a free outdoor showing of the tender animated adventure.", cost: "Free", source: "Buffalo Olmsted Parks", url: "https://www.bfloparks.org/event/movie-nights/2026-08-14/", mapUrl: "https://www.google.com/maps/search/?api=1&query=Prospect+Park+Connecticut+Street+Buffalo+NY", tags: ["Movie", "Kids", "Outdoor"], accent: "purple", setting: "outdoor" },
  { id: "festival-india", area: "city", town: "Buffalo", day: "SAT", date: "Sat, Aug 15", time: "2–8 PM", title: "Festival of India", venue: "Canalside", distance: 19, description: "A waterfront celebration of Indian dance, music, food, art and community designed to welcome every age.", cost: "Free", source: "Buffalo Waterfront", url: "https://buffalowaterfront.com/events/festivalofindia", mapUrl: "https://www.google.com/maps/search/?api=1&query=Canalside+44+Prime+Street+Buffalo+NY", tags: ["Festival", "Food", "Music"], accent: "coral", image: "/events/festival-of-india.jpg", setting: "outdoor" },
  { id: "bisons", area: "city", town: "Buffalo", day: "SUN", date: "Sun, Aug 16", time: "6:35 PM first pitch", title: "Bisons Super Hero Night", venue: "Sahlen Field", distance: 19, description: "A family baseball night with Marvel comic giveaways, costume photos and postgame fireworks.", cost: "$22 single · $99 family pack", source: "Buffalo Bisons", url: "https://www.milb.com/buffalo/events/marvel", mapUrl: "https://www.google.com/maps/search/?api=1&query=Sahlen+Field+1+James+D+Griffin+Plaza+Buffalo+NY", tags: ["Baseball", "Kids", "Fireworks"], accent: "sun", setting: "outdoor" },
  { id: "au-some", area: "city", town: "Buffalo", day: "TUE", date: "Tue, Aug 18", time: "9:30–11:30 AM", title: "Au-Some Morning Edition", venue: "Explore & More Children’s Museum", distance: 19, description: "A sensory-friendly museum morning welcomes autistic children, friends and families for calm play, art and tinkering.", cost: "Free · registration required", source: "Explore & More", url: "https://exploreandmore.org/education/au-some-evenings/", mapUrl: "https://www.google.com/maps/search/?api=1&query=Explore+and+More+130+Main+Street+Buffalo+NY", tags: ["Sensory-friendly", "Museum", "Kids"], accent: "mint", setting: "indoor" },
];

export const fallbackEvents: EventPick[] = [
  { ...legacyFallbackEvents[0], dateKey: "2026-08-12" },
  { id: "op-cruise", area: "southtowns", town: "Orchard Park", day: "TODAY", date: "Wed, Aug 12", dateKey: "2026-08-12", time: "4:30–8 PM", title: "Cruise Night at the Depot", venue: "Orchard Park BR&P Depot", distance: 1, description: "Classic cars gather at the historic train depot for a close-to-home evening with food available.", cost: "Free admission", source: "WNY Railway Historical Society", url: "https://www.wnyrhs.org/orchard-park-depot-events", mapUrl: "https://www.google.com/maps/search/?api=1&query=Orchard+Park+BRP+Depot", tags: ["Classic cars", "Depot", "Local"], accent: "mint", today: true, kind: "Community", setting: "both" },
  { id: "hamburg-concert", area: "southtowns", town: "Hamburg", day: "TODAY", date: "Wed, Aug 12", dateKey: "2026-08-12", time: "7–9 PM", title: "Summer Concert in Memorial Park", venue: "Hamburg Memorial Park", distance: 8, description: "The Village of Hamburg closes its free, family-friendly summer concert season in the park.", cost: "Free", source: "Village of Hamburg", url: "https://villageofhamburgny.gov/summerconcertsinthepark", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hamburg+Memorial+Park", tags: ["Concert", "Family", "Outdoor"], accent: "sky", today: true, kind: "Live music", setting: "outdoor" },
  { id: "ea-market", area: "southtowns", town: "East Aurora", day: "TODAY", date: "Wed, Aug 12", dateKey: "2026-08-12", time: "7 AM–1 PM", title: "East Aurora Farmers Market", venue: "115 Riley St · Classic Rink", distance: 12, description: "Browse produce, meat, cheese, flowers, baked goods and other local farm products.", cost: "Free entry", source: "Erie Grown", url: "https://www3.erie.gov/eriegrown/growers/east-aurora-farmers-market", mapUrl: "https://www.google.com/maps/search/?api=1&query=115+Riley+Street+East+Aurora+NY", tags: ["Farmers market", "Produce", "Local"], accent: "sun", today: true, kind: "Markets & food", setting: "outdoor" },
  { id: "west-seneca-market", area: "southtowns", town: "West Seneca", day: "THU", date: "Thu, Aug 13", dateKey: "2026-08-13", time: "4–7 PM", title: "West Seneca Farmers Market · Kids Day", venue: "West Seneca Town Center", distance: 9, description: "More than 50 local vendors, dinner options, acoustic music and extra kids activities fill the Town Center lawn.", cost: "Free entry", source: "Town of West Seneca", url: "https://www.westseneca.gov/DocumentCenter/View/760/Summer-2026-Newsletter-FINAL?bidId=", mapUrl: "https://www.google.com/maps/search/?api=1&query=West+Seneca+Town+Center", tags: ["Farmers market", "Kids Day", "Food"], accent: "purple", kind: "Markets & food", setting: "outdoor" },
  { id: "bills", area: "southtowns", town: "Orchard Park", day: "SAT", date: "Sat, Aug 15", dateKey: "2026-08-15", time: "1 PM", title: "Buffalo Bills vs. Carolina Panthers", venue: "Highmark Stadium", distance: 3, description: "The Bills open their preseason at home, putting a major sporting event right in Orchard Park.", cost: "Ticket prices vary", source: "Buffalo Bills", url: "https://www.buffalobills.com/schedule/", mapUrl: "https://www.google.com/maps/search/?api=1&query=Highmark+Stadium+Orchard+Park+NY", tags: ["Football", "Home game", "Tickets"], accent: "coral", kind: "Sports & active", setting: "outdoor" },
  { id: "hamburg-market", area: "southtowns", town: "Hamburg", day: "SAT", date: "Sat, Aug 15", dateKey: "2026-08-15", time: "7:30 AM–1 PM", title: "Hamburg Farmers Market", venue: "45 Church St", distance: 8, description: "Shop a deep lineup of local growers and producers at this rain-or-shine Southtowns market.", cost: "Free entry", source: "Erie Grown", url: "https://www3.erie.gov/eriegrown/eriegrown/eriegrown/growers/hamburg-farmers-market", mapUrl: "https://www.google.com/maps/search/?api=1&query=45+Church+Street+Hamburg+NY", tags: ["Farmers market", "Local food", "Rain or shine"], accent: "mint", kind: "Markets & food", setting: "outdoor" },
  { id: "op-market", area: "southtowns", town: "Orchard Park", day: "MON", date: "Mon, Aug 17", dateKey: "2026-08-17", time: "4–7 PM", title: "Village of Orchard Park Farmers Market", venue: "Historic Orchard Park Train Depot", distance: 1, description: "Local produce and community vendors gather at the depot for a convenient Monday evening market.", cost: "Free entry", source: "WNY Railway Historical Society", url: "https://www.wnyrhs.org/orchard-park-depot-events", mapUrl: "https://www.google.com/maps/search/?api=1&query=Orchard+Park+Train+Depot", tags: ["Farmers market", "Local", "Depot"], accent: "sun", kind: "Markets & food", setting: "outdoor" },
];
